core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),

]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
	document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views
app_name='products'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('faq/', views.faq, name='faq'),
    path('terms/', views.terms, name='terms'),
    path('contacts/', views.contacts, name='contacts'),
    path('products/', views.product_list, name='products'),
	path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

products/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class BannerImage(models.Model):
    image = ProcessedImageField(null=True, upload_to="banner/", 
                                           processors=[ResizeToFill(1500, 800)],
                                           format='JPEG')
    class Meta:
        verbose_name = "Изображение баннера"
        verbose_name_plural = "Изображения баннеров"
class Size(models.Model):
    size = models.CharField(max_length=4, default='S')
    class Meta:
        verbose_name = "размер"

    
class Category(models.Model):
    category_name=models.CharField(max_length=255, verbose_name = "название")
    slug = models.SlugField(max_length=255, unique=True, null=True)


    def __str__(self):
        return self.category_name
    def get_absolute_url(self):
        return reverse('products:product_list_by_category',args=[self.slug])

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"



YEARS=[('2017', '2017'), 
('2018', '2018'),
('2019', '2019'),
 ('2020', '2020'), 
 ('2021', '2021'),
  ('2022', '2022'), 
  ('2023', '2023'), 
  ('2024', '2024'),
   ('2025', '2025')]



class Product(models.Model):
    name= models.CharField(max_length=255, verbose_name = "название")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, unique=True,null=True)
    description = models.CharField(max_length=255, verbose_name = "описание")
    pub_date = models.DateField(default=timezone.now, verbose_name = "дата публикации")
    year=models.CharField(max_length=256, choices=YEARS, default='2022',  verbose_name = "коллекция")
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)    
    image2=models.ImageField(null=True, upload_to='products/%Y/%m/%d')
    image3=models.ImageField(null=True, upload_to='products/%Y/%m/%d')
    size=models.ManyToManyField(Size)
    #material
    length=models.CharField(max_length=256, choices=[('длинная', 'длинная'), ('короткая', 'короткая'),('средний', 'средний')], default='длинная',  verbose_name = "длина")
    length_hand=models.CharField(max_length=256, choices=[('длинная', 'длинная'), ('короткая', 'короткая'),('средний', 'средний'),('нет', 'нет')], default='короткая',  verbose_name = "длина рукава")
    #brand
    
    #fason
    image_thumbnail = ProcessedImageField(null=True, upload_to="products/%Y/%m/%d", 
                                           processors=[ResizeToFill(660, 1000)],
                                           format='JPEG')

   
 


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_detail',   args=[self.id, self.slug])
    class Meta:
        verbose_name_plural = "Одежда"
        ordering=("-pub_date",)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to = 'images/')
 
    def __str__(self):
        return self.product.name

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category, BannerImage
# Create your views here.


def index(request):
    banner=BannerImage.objects.all()
    
    return render(request, 'index.html', {'banner':banner})

def about_us(request):
    return render(request, 'about-us.html', {})

def faq(request):
    return render(request, 'faq.html', {})

def terms(request):
    return render(request, 'terms.html', {})

def contacts(request):
    return render(request, 'contacts.html', {})



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                    'product_list.html',
                    {'category': category,
                    'categories': categories,
                    'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                            id=id,
                            slug=slug)
    return render(request,  'product_detail.html',   {'product': product})

templates/about-us.html
{% extends "base.html" %}
{% load static %} 

 {% block content %}


    
    <div id="main-wrapper"> 

      <div class="rq-page-content">
        <div class="blog-post-single-wrapper">
          <div class="single-post-feature-img">
            <img src="{% static 'assets/dist/img/post-single/image4.jpg' %}" alt="">
          </div>
          <div class="container">
            <div class="rq-content-block">
              <div class="rq-title-container bredcrumb-title text-center">
                <h2 class="rq-title">О компании</h2>
                <ol class="breadcrumb rq-subtitle">
                  <li><a href="/">ГЛАВНАЯ</a></li>
                  <li class="active">О компании</li>
                </ol>
              </div>
              
              <div class="post-content">
           
<p style="font-size: 20px" >
	
	Что делать, если у вас скоро особенное мероприятие, а Вам совершенно нечего одеть и все ваши поиски подходящего наряда и образа не увенчались успехом. А если платье очень понравилось, но вас огорчает цена, тем более, что потом оно просто будет висеть в шкафу? Идеальный вариант, взять напрокат у нас♥️ Приятный бонус этого простого волшебства – двойная экономия:<br><br>

			<i>места в вашем шкафу;<br>
денег в вашем кошельке.</i>
</p>

			<p style="font-size: 20px" >
Прямо сейчас в салоне Velvet Dresses в наличии более 300 платьев, каждое из которых находится в идеальном состоянии – чистое, поглаженное и без постороннего запаха. Волнуетесь о том, хорошо ли сядет наряд? Нет никаких причин для переживаний: мы подгоним понравившееся платье именно под вашу фигуру!</p>
.
			<p style="font-size: 20px" >


Коллекция Velvet Dresses постоянно обновляется. Платья, которые были в прокате уже много раз, мы продаем. Кстати, по ценам, низким для одежды в столь хорошем состоянии! Не подошел ни один наряд из каталога салона? Возможен пошив на заказ по вашему фото или эскизу</p>
		</div><!-- /.inner-element -->	
	</div><!-- /.container -->
</div><!-- /.mission -->



              </div>




		</div><!-- /.row -->
	</div><!-- /.container -->
</div><!-- /.team -->
 


 




 







  {% endblock content %}

templates/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">     
  <head>
    <meta charset="UTF-8"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Velvet-Dresses.uz | ПРОКАТ ЭКСЛЮЗИВНЫХ ПЛАТЬЕВ </title>
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Forum|Open+Sans:400,600|Roboto:100,300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/dist/style/elements.css' %}">
    <link rel="stylesheet" href="{% static 'assets/dist/style/dateRangePicker.css' %}">
    <link rel="stylesheet" href="{% static 'assets/dist/style/header.css' %}">
    <link rel="stylesheet" href="{% static 'assets/dist/style/footer.css' %}">
    <link rel="stylesheet" href="{% static 'assets/dist/style/blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/dist/style/call.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/dist/img/favicon.ico' %}">
</head>
<body>
    <!-- ==========================-->
<!-- LOADER-->
<!-- ==========================-->
<div id="gl-circle-loader-wrapper">
  <div id="gl-circle-loader-center">
    <div class="gl-circle-load">
      <img src="{% static 'assets/dist/img/ploading.gif' %}" alt="Page Loader">
    </div>
  </div>
</div>

<!-- <div class="top-bar" id="top_bar"> 
    <div class="container">
        <p class="font-14-ope-reg-0 text-center margin-0">…Enjoy 20% off when you sign up to become a member...</p>
        <i class="ion-ios-close-empty"></i>
    </div>
</div>   -->
<header class="main-nav" id="stickynav">
<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
         <a class="navbar-brand font-36-pla-reg-2" href='/'><img src="{% static 'assets/dist/img/logo.png' %}" alt="logo" /></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
            <li class="active"><a href='/'>ГЛАВНАЯ</a></li>
            <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Коллекция</a>
          <ul class="dropdown-menu number2">
            <li><a href="listing-page-list.html">List View</a></li>
            <li><a href="listing-page2.html">Grid View</a></li>
            <li><a href="listing-page.html">Grid View 2</a></li>
          </ul>
        </li> -->
            <li class="dropdown">
                <a href='' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Коллекция</a>
                <ul class="dropdown-menu">
                    <li class="rq-mega-sks">
                        <div class="row">
                            <div class="col-sm-6">
                              {% for c in categories %}
                                <a style='font-size: 19px; font-weight: 550' href="{% url 'products:products' %}">{{ c.category_name}}</a>

                               <!--  <a href="#">Мусульманские платья</a> 
                                <a href="#">Вечерние платья</a>
                                <a href="#">Коктелние платья</a>
                                <a href="#">Мусульманские платья</a>  -->
                                {% endfor %}
                            </div>
                            
                            
                            
                            <div class="col-sm-6">
                                <figure>
                                    <img src="{% static 'assets/dist/img/content/4.jpg' %}"  alt="1" class="img-responsive">
                                </figure>
                            </div>
                        </div>
                    </li>
                </ul>
            </li>
        <li><a href="{% url 'products:terms' %}" >условия</a></li>
        
                
        <li><a href="{% url 'products:about_us' %}" >О НАС</a></li>
        <li><a href="{% url 'products:faq' %}" >Вопрос-Ответ</a></li>
        <li><a href="{% url 'products:contacts' %}" >КОНТАКТЫ</a></li>
        
        
        </ul>
</nav>

<ul class="nav navbar-nav dr-cart">

        <li><a href="tel:998-71-268-48-47" style="color: white; font-size: 18px;" >998-71-268-48-47</a></li>

    
  
  
</ul>





</header><!-- /.End header -->
<a href="tel:998-71-268-48-47" class="float" style='color:white;' target="_blank">
<i class="fa fa-phone my-float"></i>
</a> 

<!--Trigger-->

<style>
  /*Trigger Button*/
.login-trigger {
  color: #fff;
  background:#691f1f;
  padding: 15px 30px;
  position: relative; 
}

/*Modal*/
h4 {
  font-weight: bold;
  color: #fff;
}
.close {
  color: #fff;
  transform: scale(1.2)
}
.modal-content {
  font-weight: bold;
  background: #691f1f;
}
.form-control {
  margin: 1em 0;
}
.form-control:hover, .form-control:focus {
  box-shadow: none;  
  border-color: #fff;
}
.username, .password {
  border: none;
  border-radius: 0;
  box-shadow: none;
  border-bottom: 2px solid #eee;
  padding-left: 0;
  font-weight: normal;
  background: transparent;  
}
.form-control::-webkit-input-placeholder {
  color: #fff;  
}
.form-control:focus::-webkit-input-placeholder {
  font-weight: bold;
  color: #fff;
}
.login {
  padding: 6px 20px;

  background: white;
  color: #691f1f;
  font-weight: bold;
  transition: all .5s;
  margin-top: 1em;
}
.login:hover {
  font-size: 15px;
}</style>
<!--Trigger-->


<div id="login" class="modal fade" role="dialog">
  <div class="modal-dialog">
    
    <div class="modal-content">
      <div class="modal-body">
        <button data-dismiss="modal" class="close">&times;</button>
        <h4>Закажите бесплатный звонок 
          <br>или позвоните прямо сейчас на <a style="color: white; font-weight: 600" href="tel:998-71-268-48-47"> 998-71-268-48-47</a></h4>
        <form>
          <input type="text" name="username" class="username form-control" placeholder="Имя"/>
          <input type="tel" name="password" class="password form-control" placeholder="Телефон"/>
          <input class="btn login" type="submit" value="Отправить" />
        </form>
      </div>
    </div>
  </div>  
</div>

{% block content %}
  {% endblock content %}



<footer class="main-footer">
    <div class="footer">
        <div class="rq-container"> 
            <div class="item1">
                <a href="/" class="font-36-pla-reg-2"><img src="{% static 'assets/dist/img/logo1.png' %}" alt="logo" /></a>
                <p>Прямо сейчас в салоне Velvet Dresses в наличии более 300 платьев, каждое из которых находится в идеальном состоянии – чистое, поглаженное и без постороннего запаха. Волнуетесь о том, хорошо ли сядет наряд? Нет никаких причин для переживаний: мы подгоним понравившееся платье именно под вашу фигуру!</p>
                <div class="get-touch">
                    <ul class="list-unstyled">
                        <li><a href="www.t.me/velvet_dresses"><i class="fa fa-facebook" ></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-mail" aria-hidden="true"></i></a></li>
                    </ul>
                </div><!-- /.get-touch -->
            </div><!-- /.item1 -->
              <div class="item4">
               <h3 style="margin-left:130px;"></h3>
             </div>
           
            <div class="item3">
                <h3 class="font-18-pla-reg-2">GET HELP</h3>
                <ul class="list-unstyled">
                    <li><a href="/">ГЛАВНАЯ</a></l[.]i>
                   <li><a href="{% url 'products:products' %}">КОЛЛЕКЦИЯ </a></li>
                   <li><a href="{% url 'products:terms' %}"> УСЛОВИЯ</a></li>
                    <li><a href="{% url 'products:about_us' %}">О НАС</a></li> 
                    <li><a href="{% url 'products:contacts' %}">КОНТАКТЫ</a></li> 
                    <li><a href="{% url 'products:faq' %}">ВОПРОСЫ-ОТВЕТЫ</a></li>
                </ul>
            </div><!-- /.item2 -->
      
             <div class="item4">
               <h3 style="margin-left:130px;"></h3>
             </div>
           
            
            <div class="item5">
                <h3 class="font-18-pla-reg-2">Контакты </h3>
                <ul class="list-unstyled contact">
                    <li class="map-marker"><p>Буюк Ипак Йули 103 дом 69 кв. <br> Ориентир: Мир Подарков </p>
                        <p>Ташкент, Узбекистан</p></li>
                    <li class="phone"><p>+998712684847</p></li>
                    <li class="mobile"><p>+998994844670</p></li>
                    <li class="envelope"><p>mailto@velvet-dresses.uz</p></li>
                </ul>
            </div><!-- /.item5 -->
           
        </div><!-- /.rq-container -->
    </div><!-- /.footer --> 
    <div class="bottom-bar">
        <p>Copyright 2021 &copy; <a href="#">VELVET DRESSES</a></p>
    </div><!-- /.bottom-bar -->
</footer>





  <script src="{% static 'assets/dist/js/vendor/jquery-3.2.0.min.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/countUp.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/owl.carousel.min.js' %}"></script> 
  <script src="{% static 'assets/dist/js/vendor/ion.rangeSlider.min.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/dateRangePicker.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/jquery.flexslider-min.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/select2.min.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/lightbox.min.js' %}"></script>
  <script src="{% static 'assets/dist/js/vendor/jquery.smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/dist/js/custom.js' %}"></script>
  <script src="{% static 'assets/dist/js/call.js' %}"></script>

</body>
</html>

templates/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active" style="color:#6b2025"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
    {% endif %}

templates/product_detail.html
{% extends "base.html" %}
{% load static %} 

 {% block content %}


<div class="container">
  <ol class="breadcrumb underline"> 
    <li><a href='/'>ГЛАВНАЯ</a></li>
    <li><a href="{% url 'products:products' %}">Все платья</a></li>
    <li>{{product.name}}</li>
  </ol><!-- /.breadcrumb --> 
</div><!-- /.container -->  
 

<div class="product-details base-padd"> 
	<div class="container">
		<div class="row">
			<div class="col-sm-5 rq-custom-5">
				<div class="flexslider product_details_slider"> 
				  <ul class="slides">

				 
				    <li data-thumb="{{product.image.url }}"><!-- There is a mistake  -->
				      <img  src="{{product.image.url }}" class="img-responsive" alt="1" />
				    </li>
				    
				    <li data-thumb="{{product.image2.url }}">
				      <img src="{{product.image.url }}"  alt="1"/>
				    </li>
				    <li data-thumb="{{product.image3.url }}">
				      <img src="{{product.image.url }}"  alt="1"/>
				    </li>
				  </ul>
				  <!-- <a href="#"><img weight="400" height="500" src="{{product.image.url }}" alt="1"></a> -->
				  
				</div><!-- /.product_details_slider -->
			</div><!-- /.col-sm-5 -->
			<div class="col-sm-7">
				<div class="rq-inner">
						
					<a href="#" class="font-30-for-reg-0">{{product.name}}</a>
					<hr>

					<h4> <small>Бренд: <span>{{product.brand}}</span></small></h4>
					<h4> <small>размер: {{product.size}}</small> </h4>	
<br>
					<a href="#" class="rating" >
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						
					</a><!-- /.rating -->
					<h4 style="font-size: 18px;"> <span> до 70% экономии по сравнению с покупкой </span> </h4>
					
					
						
					

				
					
				

					<div class="row rq-margin">
						<div class="col-sm-6">

							<a  href="tel:998-71-268-48-47" class="reserve" style="background-color: #691919; padding-bottom: 12px; width: 200px; height: 30px;"><i class="fa fa-phone"> Запись на примерку </i></a>	
								
						</div><!-- /.col-sm-6 -->
						<div class="col-sm-6">
							<div class="social-icon">
								<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
								<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
								<a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
								<a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
							</div>	
						</div><!-- /.col-sm-6 -->
					</div><!-- /.row -->

					<div class="panel-group rq-accordion" id="accordion" role="tablist" aria-multiselectable="true">
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingOne">
					      <h4 class="panel-title">
					        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
					          Size and fit
					          <i class="fa fa-angle-up pull-right" aria-hidden="true"></i>
					        </a>

					      </h4>
					    </div>
					    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">

					      <div class="panel-body">
					        Lorem Ipsum is simply dummy text of the printing and type setting industry. Itting industry. Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum is simply dummy text of the printing and type setting industry.
					      </div>
					    </div>
					  </div>
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingTwo">
					      <h4 class="panel-title">
					        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
					          Dsigner notes
					          <i class="fa fa-angle-down pull-right" aria-hidden="true"></i>
					        </a>
					      </h4>
					    </div>
					    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
					      <div class="panel-body">
					        Lorem Ipsum is simply dummy text of the printing and type setting industry. Itting industry. Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum is simply dummy text of the printing and type setting industry.
					      </div>
					    </div>
					  </div>
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingThree">
					      <h4 class="panel-title">
					        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
					          Product details
					          <i class="fa fa-angle-down pull-right" aria-hidden="true"></i>
					        </a>
					      </h4>
					    </div>
					    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
					      <div class="panel-body">
					       Lorem Ipsum is simply dummy text of the printing and type setting industry. Itting industry. Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum is simply dummy text of the printing and type setting industry.
					      </div>
					    </div>
					  </div>
					</div><!-- /.accordion -->

				</div><!-- /.rq-inner -->
			</div><!-- /.col-lg-7 -->
		</div><!-- /.row
 -->		
	</div>	<!-- /.container -->
	<div class="container complete-look">
		<h4 class="font-30-for-reg-3">Complete the look</h4>
		<div class="row">
			<div class="col-sm-4">
				<div class="inner">
					<img src="../assets/dist/img/complete-look/1.jpg" alt="">
					<div class="hover">
						<a class="font-18-for-reg-1" href="#">Quick View</a>
					</div><!-- /.hover -->
				</div><!-- /.inner -->
			</div><!-- /.col-sm-4 -->
			<div class="col-sm-4">
				<div class="inner">
					<img src="../assets/dist/img/complete-look/2.jpg" alt="">
					<div class="hover">
						<a class="font-18-for-reg-1" href="#">Quick View</a>
					</div><!-- /.hover -->
				</div><!-- /.inner -->
			</div><!-- /.col-sm-4 -->
			<div class="col-sm-4">
				<div class="inner">
					<img src="../assets/dist/img/complete-look/3.jpg" alt="">
					<div class="hover">
						<a class="font-18-for-reg-1" href="#">Quick View</a>
					</div><!-- /.hover -->
				</div><!-- /.inner -->
			</div><!-- /.col-sm-4 -->
		</div><!-- /.row -->
	</div><!-- /.container -->
</div><!-- /.product-details -->	



<div class="favorites base-padd">
<h2>новая коллекция</h2>
	<div class="container">
		<div class="owl-favorites owl-carousel owl-theme">

{% for product in products %}
	    <div class="item">
	    	<figure> 
	    		<img src="{{product.image_thumbnail.url}}"  alt="{{product.name}}">
	    		<a href="{{product.get_absolute_url}}">Aрендовать</a>
	    	</figure>
	    	<h3 class="font-20-for-reg-0">{{product.name}}</h3>	
	    	<p class="font-16-for-reg-0">{{product.description }}</p>
	    </div>
	    	{% endfor %}
	 
    </div><!-- /.owl-favorites -->
	</div><!-- /.container -->
</div><!-- /.favorites -->






 {% endblock content %}




  

templates/termss.html
{% extends "base.html" %}
{% load static %} 

 {% block content %}

 УСЛОВИЯ АРЕНДЫ ПЛАТЬЯ В VELVET DRESSES 
___________________________________
✔️Записаться на примерку по телефону +998 71-268-48-47

✔️Приехать в салон . Подобрать платье . ( Вы можете забронировать платье на желаемую дату или арендовать день в день ,если платье свободно на ваши даты )

✔️Оплатить стоимость аренды и оставить залог ( залог возвращается при сдаче Платья обратно в салон )

✔️Аренда осуществляется только при наличии ПАСПОРТА. 

✔️Вернуть платье в указанный срок 

Милые девушки , сообщаем ,что вы несёте юридическую ответственность за сохранность платья / аксессуаров VELVET DRESSES ❤️ 

ВАЖНО : если по какой-либо причине вы отказываетесь от Забронированного Платья ,то сумма задатка не возвращается 


 {% endblock content %}